// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apipausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	versioned "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned"
	internalinterfaces "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/informers/externalversions/internalinterfaces"
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/listers/pausing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBDatacenterClaimInformer provides access to a shared informer and lister for
// ScyllaDBDatacenterClaims.
type ScyllaDBDatacenterClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() pausingv1alpha1.ScyllaDBDatacenterClaimLister
}

type scyllaDBDatacenterClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScyllaDBDatacenterClaimInformer constructs a new informer for ScyllaDBDatacenterClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScyllaDBDatacenterClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterClaimInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScyllaDBDatacenterClaimInformer constructs a new informer for ScyllaDBDatacenterClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScyllaDBDatacenterClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PausingV1alpha1().ScyllaDBDatacenterClaims(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PausingV1alpha1().ScyllaDBDatacenterClaims(namespace).Watch(context.TODO(), options)
			},
		},
		&apipausingv1alpha1.ScyllaDBDatacenterClaim{},
		resyncPeriod,
		indexers,
	)
}

func (f *scyllaDBDatacenterClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterClaimInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scyllaDBDatacenterClaimInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apipausingv1alpha1.ScyllaDBDatacenterClaim{}, f.defaultInformer)
}

func (f *scyllaDBDatacenterClaimInformer) Lister() pausingv1alpha1.ScyllaDBDatacenterClaimLister {
	return pausingv1alpha1.NewScyllaDBDatacenterClaimLister(f.Informer().GetIndexer())
}
