// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apipausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	versioned "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned"
	internalinterfaces "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/informers/externalversions/internalinterfaces"
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/listers/pausing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBDatacenterPoolInformer provides access to a shared informer and lister for
// ScyllaDBDatacenterPools.
type ScyllaDBDatacenterPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() pausingv1alpha1.ScyllaDBDatacenterPoolLister
}

type scyllaDBDatacenterPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewScyllaDBDatacenterPoolInformer constructs a new informer for ScyllaDBDatacenterPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewScyllaDBDatacenterPoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterPoolInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredScyllaDBDatacenterPoolInformer constructs a new informer for ScyllaDBDatacenterPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredScyllaDBDatacenterPoolInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PausingV1alpha1().ScyllaDBDatacenterPools(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PausingV1alpha1().ScyllaDBDatacenterPools(namespace).Watch(context.TODO(), options)
			},
		},
		&apipausingv1alpha1.ScyllaDBDatacenterPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *scyllaDBDatacenterPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredScyllaDBDatacenterPoolInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *scyllaDBDatacenterPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apipausingv1alpha1.ScyllaDBDatacenterPool{}, f.defaultInformer)
}

func (f *scyllaDBDatacenterPoolInformer) Lister() pausingv1alpha1.ScyllaDBDatacenterPoolLister {
	return pausingv1alpha1.NewScyllaDBDatacenterPoolLister(f.Informer().GetIndexer())
}
