// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type PausableScyllaDBDatacenterExpansion interface{}

type ScyllaDBDatacenterClaimExpansion interface{}

type ScyllaDBDatacenterPoolExpansion interface{}
