// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PausableScyllaDBDatacenterListerExpansion allows custom methods to be added to
// PausableScyllaDBDatacenterLister.
type PausableScyllaDBDatacenterListerExpansion interface{}

// PausableScyllaDBDatacenterNamespaceListerExpansion allows custom methods to be added to
// PausableScyllaDBDatacenterNamespaceLister.
type PausableScyllaDBDatacenterNamespaceListerExpansion interface{}

// ScyllaDBDatacenterClaimListerExpansion allows custom methods to be added to
// ScyllaDBDatacenterClaimLister.
type ScyllaDBDatacenterClaimListerExpansion interface{}

// ScyllaDBDatacenterClaimNamespaceListerExpansion allows custom methods to be added to
// ScyllaDBDatacenterClaimNamespaceLister.
type ScyllaDBDatacenterClaimNamespaceListerExpansion interface{}

// ScyllaDBDatacenterPoolListerExpansion allows custom methods to be added to
// ScyllaDBDatacenterPoolLister.
type ScyllaDBDatacenterPoolListerExpansion interface{}

// ScyllaDBDatacenterPoolNamespaceListerExpansion allows custom methods to be added to
// ScyllaDBDatacenterPoolNamespaceLister.
type ScyllaDBDatacenterPoolNamespaceListerExpansion interface{}
