// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PausableScyllaDBDatacenterLister helps list PausableScyllaDBDatacenters.
// All objects returned here must be treated as read-only.
type PausableScyllaDBDatacenterLister interface {
	// List lists all PausableScyllaDBDatacenters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.PausableScyllaDBDatacenter, err error)
	// PausableScyllaDBDatacenters returns an object that can list and get PausableScyllaDBDatacenters.
	PausableScyllaDBDatacenters(namespace string) PausableScyllaDBDatacenterNamespaceLister
	PausableScyllaDBDatacenterListerExpansion
}

// pausableScyllaDBDatacenterLister implements the PausableScyllaDBDatacenterLister interface.
type pausableScyllaDBDatacenterLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.PausableScyllaDBDatacenter]
}

// NewPausableScyllaDBDatacenterLister returns a new PausableScyllaDBDatacenterLister.
func NewPausableScyllaDBDatacenterLister(indexer cache.Indexer) PausableScyllaDBDatacenterLister {
	return &pausableScyllaDBDatacenterLister{listers.New[*pausingv1alpha1.PausableScyllaDBDatacenter](indexer, pausingv1alpha1.Resource("pausablescylladbdatacenter"))}
}

// PausableScyllaDBDatacenters returns an object that can list and get PausableScyllaDBDatacenters.
func (s *pausableScyllaDBDatacenterLister) PausableScyllaDBDatacenters(namespace string) PausableScyllaDBDatacenterNamespaceLister {
	return pausableScyllaDBDatacenterNamespaceLister{listers.NewNamespaced[*pausingv1alpha1.PausableScyllaDBDatacenter](s.ResourceIndexer, namespace)}
}

// PausableScyllaDBDatacenterNamespaceLister helps list and get PausableScyllaDBDatacenters.
// All objects returned here must be treated as read-only.
type PausableScyllaDBDatacenterNamespaceLister interface {
	// List lists all PausableScyllaDBDatacenters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.PausableScyllaDBDatacenter, err error)
	// Get retrieves the PausableScyllaDBDatacenter from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pausingv1alpha1.PausableScyllaDBDatacenter, error)
	PausableScyllaDBDatacenterNamespaceListerExpansion
}

// pausableScyllaDBDatacenterNamespaceLister implements the PausableScyllaDBDatacenterNamespaceLister
// interface.
type pausableScyllaDBDatacenterNamespaceLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.PausableScyllaDBDatacenter]
}
