// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBDatacenterClaimLister helps list ScyllaDBDatacenterClaims.
// All objects returned here must be treated as read-only.
type ScyllaDBDatacenterClaimLister interface {
	// List lists all ScyllaDBDatacenterClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.ScyllaDBDatacenterClaim, err error)
	// ScyllaDBDatacenterClaims returns an object that can list and get ScyllaDBDatacenterClaims.
	ScyllaDBDatacenterClaims(namespace string) ScyllaDBDatacenterClaimNamespaceLister
	ScyllaDBDatacenterClaimListerExpansion
}

// scyllaDBDatacenterClaimLister implements the ScyllaDBDatacenterClaimLister interface.
type scyllaDBDatacenterClaimLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.ScyllaDBDatacenterClaim]
}

// NewScyllaDBDatacenterClaimLister returns a new ScyllaDBDatacenterClaimLister.
func NewScyllaDBDatacenterClaimLister(indexer cache.Indexer) ScyllaDBDatacenterClaimLister {
	return &scyllaDBDatacenterClaimLister{listers.New[*pausingv1alpha1.ScyllaDBDatacenterClaim](indexer, pausingv1alpha1.Resource("scylladbdatacenterclaim"))}
}

// ScyllaDBDatacenterClaims returns an object that can list and get ScyllaDBDatacenterClaims.
func (s *scyllaDBDatacenterClaimLister) ScyllaDBDatacenterClaims(namespace string) ScyllaDBDatacenterClaimNamespaceLister {
	return scyllaDBDatacenterClaimNamespaceLister{listers.NewNamespaced[*pausingv1alpha1.ScyllaDBDatacenterClaim](s.ResourceIndexer, namespace)}
}

// ScyllaDBDatacenterClaimNamespaceLister helps list and get ScyllaDBDatacenterClaims.
// All objects returned here must be treated as read-only.
type ScyllaDBDatacenterClaimNamespaceLister interface {
	// List lists all ScyllaDBDatacenterClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.ScyllaDBDatacenterClaim, err error)
	// Get retrieves the ScyllaDBDatacenterClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pausingv1alpha1.ScyllaDBDatacenterClaim, error)
	ScyllaDBDatacenterClaimNamespaceListerExpansion
}

// scyllaDBDatacenterClaimNamespaceLister implements the ScyllaDBDatacenterClaimNamespaceLister
// interface.
type scyllaDBDatacenterClaimNamespaceLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.ScyllaDBDatacenterClaim]
}
