// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ScyllaDBDatacenterPoolLister helps list ScyllaDBDatacenterPools.
// All objects returned here must be treated as read-only.
type ScyllaDBDatacenterPoolLister interface {
	// List lists all ScyllaDBDatacenterPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.ScyllaDBDatacenterPool, err error)
	// ScyllaDBDatacenterPools returns an object that can list and get ScyllaDBDatacenterPools.
	ScyllaDBDatacenterPools(namespace string) ScyllaDBDatacenterPoolNamespaceLister
	ScyllaDBDatacenterPoolListerExpansion
}

// scyllaDBDatacenterPoolLister implements the ScyllaDBDatacenterPoolLister interface.
type scyllaDBDatacenterPoolLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.ScyllaDBDatacenterPool]
}

// NewScyllaDBDatacenterPoolLister returns a new ScyllaDBDatacenterPoolLister.
func NewScyllaDBDatacenterPoolLister(indexer cache.Indexer) ScyllaDBDatacenterPoolLister {
	return &scyllaDBDatacenterPoolLister{listers.New[*pausingv1alpha1.ScyllaDBDatacenterPool](indexer, pausingv1alpha1.Resource("scylladbdatacenterpool"))}
}

// ScyllaDBDatacenterPools returns an object that can list and get ScyllaDBDatacenterPools.
func (s *scyllaDBDatacenterPoolLister) ScyllaDBDatacenterPools(namespace string) ScyllaDBDatacenterPoolNamespaceLister {
	return scyllaDBDatacenterPoolNamespaceLister{listers.NewNamespaced[*pausingv1alpha1.ScyllaDBDatacenterPool](s.ResourceIndexer, namespace)}
}

// ScyllaDBDatacenterPoolNamespaceLister helps list and get ScyllaDBDatacenterPools.
// All objects returned here must be treated as read-only.
type ScyllaDBDatacenterPoolNamespaceLister interface {
	// List lists all ScyllaDBDatacenterPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*pausingv1alpha1.ScyllaDBDatacenterPool, err error)
	// Get retrieves the ScyllaDBDatacenterPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*pausingv1alpha1.ScyllaDBDatacenterPool, error)
	ScyllaDBDatacenterPoolNamespaceListerExpansion
}

// scyllaDBDatacenterPoolNamespaceLister implements the ScyllaDBDatacenterPoolNamespaceLister
// interface.
type scyllaDBDatacenterPoolNamespaceLister struct {
	listers.ResourceIndexer[*pausingv1alpha1.ScyllaDBDatacenterPool]
}
