apiVersion: v1
kind: Service
metadata:
  name: pausable-scylladb-ingress
spec:
  selector:
    app.kubernetes.io/name: pausable-scylladb-ingress
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: cql-ssl
    port: 9142
    protocol: TCP
    targetPort: 8443
