kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pausable-scylladb-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pausable-scylladb-ingress
subjects:
- kind: ServiceAccount
  name: pausable-scylladb-ingress
  namespace: pausable-scylladb-ingress
