apiVersion: apps/v1
kind: Deployment
metadata:
  name: pausable-scylladb-ingress
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: pausable-scylladb-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pausable-scylladb-ingress
    spec:
      serviceAccountName: pausable-scylladb-ingress
      containers:
      - name: pausable-scylladb-ingress
        image: docker.io/rzetelskik/pausable-scylladb-operator:latest
        imagePullPolicy: Always
        command:
        - /usr/bin/pausable-scylladb-ingress
        args:
        - run
        - --ipv4-address=0.0.0.0
        - --https-port=8443
        - --loglevel=5
        securityContext:
          runAsUser:  1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        resources:
          requests:
            cpu: 100m
            memory: 50M
        ports:
        - name: https
          containerPort: 8443
