apiVersion: v1
kind: ServiceAccount
metadata:
  name: pausable-scylladb-operator
  namespace: pausable-scylladb-operator
  labels:
    app.kubernetes.io/name: pausable-scylladb-operator
    app.kubernetes.io/instance: pausable-scylladb-operator
