apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylladb:controller:pausable-scylladb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scylladb:controller:pausable-scylladb-operator
subjects:
- kind: ServiceAccount
  name: pausable-scylladb-operator
  namespace: pausable-scylladb-operator
