// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned/typed/pausing/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBDatacenterPools implements ScyllaDBDatacenterPoolInterface
type fakeScyllaDBDatacenterPools struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBDatacenterPool, *v1alpha1.ScyllaDBDatacenterPoolList]
	Fake *FakePausingV1alpha1
}

func newFakeScyllaDBDatacenterPools(fake *FakePausingV1alpha1, namespace string) pausingv1alpha1.ScyllaDBDatacenterPoolInterface {
	return &fakeScyllaDBDatacenterPools{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBDatacenterPool, *v1alpha1.ScyllaDBDatacenterPoolList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbdatacenterpools"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBDatacenterPool"),
			func() *v1alpha1.ScyllaDBDatacenterPool { return &v1alpha1.ScyllaDBDatacenterPool{} },
			func() *v1alpha1.ScyllaDBDatacenterPoolList { return &v1alpha1.ScyllaDBDatacenterPoolList{} },
			func(dst, src *v1alpha1.ScyllaDBDatacenterPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBDatacenterPoolList) []*v1alpha1.ScyllaDBDatacenterPool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBDatacenterPoolList, items []*v1alpha1.ScyllaDBDatacenterPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
