// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned/typed/pausing/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePausingV1alpha1 struct {
	*testing.Fake
}

func (c *FakePausingV1alpha1) PausableScyllaDBDatacenters(namespace string) v1alpha1.PausableScyllaDBDatacenterInterface {
	return newFakePausableScyllaDBDatacenters(c, namespace)
}

func (c *FakePausingV1alpha1) ScyllaDBDatacenterClaims(namespace string) v1alpha1.ScyllaDBDatacenterClaimInterface {
	return newFakeScyllaDBDatacenterClaims(c, namespace)
}

func (c *FakePausingV1alpha1) ScyllaDBDatacenterPools(namespace string) v1alpha1.ScyllaDBDatacenterPoolInterface {
	return newFakeScyllaDBDatacenterPools(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePausingV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
