// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned/typed/pausing/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeScyllaDBDatacenterClaims implements ScyllaDBDatacenterClaimInterface
type fakeScyllaDBDatacenterClaims struct {
	*gentype.FakeClientWithList[*v1alpha1.ScyllaDBDatacenterClaim, *v1alpha1.ScyllaDBDatacenterClaimList]
	Fake *FakePausingV1alpha1
}

func newFakeScyllaDBDatacenterClaims(fake *FakePausingV1alpha1, namespace string) pausingv1alpha1.ScyllaDBDatacenterClaimInterface {
	return &fakeScyllaDBDatacenterClaims{
		gentype.NewFakeClientWithList[*v1alpha1.ScyllaDBDatacenterClaim, *v1alpha1.ScyllaDBDatacenterClaimList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("scylladbdatacenterclaims"),
			v1alpha1.SchemeGroupVersion.WithKind("ScyllaDBDatacenterClaim"),
			func() *v1alpha1.ScyllaDBDatacenterClaim { return &v1alpha1.ScyllaDBDatacenterClaim{} },
			func() *v1alpha1.ScyllaDBDatacenterClaimList { return &v1alpha1.ScyllaDBDatacenterClaimList{} },
			func(dst, src *v1alpha1.ScyllaDBDatacenterClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ScyllaDBDatacenterClaimList) []*v1alpha1.ScyllaDBDatacenterClaim {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ScyllaDBDatacenterClaimList, items []*v1alpha1.ScyllaDBDatacenterClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
