// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/api/pausing/v1alpha1"
	pausingv1alpha1 "github.com/pausing-clusters-thesis/pausable-scylladb-operator/pkg/client/pausing/clientset/versioned/typed/pausing/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePausableScyllaDBDatacenters implements PausableScyllaDBDatacenterInterface
type fakePausableScyllaDBDatacenters struct {
	*gentype.FakeClientWithList[*v1alpha1.PausableScyllaDBDatacenter, *v1alpha1.PausableScyllaDBDatacenterList]
	Fake *FakePausingV1alpha1
}

func newFakePausableScyllaDBDatacenters(fake *FakePausingV1alpha1, namespace string) pausingv1alpha1.PausableScyllaDBDatacenterInterface {
	return &fakePausableScyllaDBDatacenters{
		gentype.NewFakeClientWithList[*v1alpha1.PausableScyllaDBDatacenter, *v1alpha1.PausableScyllaDBDatacenterList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("pausablescylladbdatacenters"),
			v1alpha1.SchemeGroupVersion.WithKind("PausableScyllaDBDatacenter"),
			func() *v1alpha1.PausableScyllaDBDatacenter { return &v1alpha1.PausableScyllaDBDatacenter{} },
			func() *v1alpha1.PausableScyllaDBDatacenterList { return &v1alpha1.PausableScyllaDBDatacenterList{} },
			func(dst, src *v1alpha1.PausableScyllaDBDatacenterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PausableScyllaDBDatacenterList) []*v1alpha1.PausableScyllaDBDatacenter {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PausableScyllaDBDatacenterList, items []*v1alpha1.PausableScyllaDBDatacenter) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
