apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwo-immediate
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: pd-ssd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
